package com.ktc.framework.skycommondefine;

import android.content.BroadcastReceiver;
import android.content.IntentFilter;

///import com.ktc.framework.skysdk.ipc.SkyContext;

public class SkyBroadcast {
    public static final String SKY_BCT_ACTION_A2DP_CONNECTION_STATE_CHANGED = "android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED";
    public static final String SKY_BCT_ACTION_RESUME = "android.intent.action.RESUME";
    public static final String SKY_BCT_ACTION_SET_3D_MODE = "ktc.acton.set.3d.mode";
    public static final String SKY_BCT_ACTION_SET_LOCAL_SCREEN_SAVER = "ktc.action.set.location.screensaver";
    public static final String SKY_BCT_ACTION_SUSPEND = "android.intent.action.SUSPEND";
    public static final String SKY_BCT_AUDIO_RESOURCE_REQUEST_RELEASE = "com.ktc.broadcast.resource.audioPlay.resume";
    public static final String SKY_BCT_AUDIO_RESOURCE_RESUME_INFO = "com.ktc.broadcast.resource.audio.resumeInfo";
    public static final String SKY_BCT_CHANGE_USER = "change_user";
    public static final String SKY_BCT_CHECK_SKYRC_BLUETOOTH_PAIR = "com.ktc.skyrc.bluetooth";
    public static final String SKY_BCT_CLEAR_FLOAT_UI = "com.ktc.broadcast.clear.float.ui";
    public static final String SKY_BCT_CLEAR_FOOTPRINT = "com.ktc.clear.footprint";
    public static final String SKY_BCT_COMMENT_VIEW = "com.ktc.broadcast.toast";
    public static final String SKY_BCT_CUSTOMER_TOKEN_CREATED = "com.ktc.customer_token.created";
    public static final String SKY_BCT_CUSTOMER_TOKEN_EXPIRED = "com.ktc.customer_token.expired";
    public static final String SKY_BCT_CUSTOMER_TOKEN_GET = "com.ktc.customer_token.get";
    public static final String SKY_BCT_DIG_ON_HOME = "com.ktc.mstar.home.window";
    public static final String SKY_BCT_DIRECTIVE = "com.ktc.directive";
    public static final String SKY_BCT_DMT_ITV_VOICEINPUT = "com.ktc.dmt.itv.voiceplatform.voicedetect.intputstatus";
    public static final String SKY_BCT_DTV_CHANGE_CHANNEL = "com.ktc.dtv.changechannel";
    public static final String SKY_BCT_DTV_CHANNEL_SEARCHED = "com.ktc.dtv.channelsearched";
    public static final String SKY_BCT_DTV_EXIT = "com.ktc.broadcast.dtv.release.ok";
    public static final String SKY_BCT_ENCYCLOPEDIAS_VIEW = "com.ktc.encyclopedias.view";
    public static final String SKY_BCT_EXIT_AUDIO_ALONE = "com.ktc.exit.audioalone";
    public static final String SKY_BCT_FACTORY_SDCARD_INITNG = "com.ktc.sdcard.initng";
    public static final String SKY_BCT_FACTORY_SDCARD_INITOK = "com.ktc.sdcard.initok";
    public static final String SKY_BCT_FAC_EXIT = "com.ktc.broadcast.factory.eixt";
    public static final String SKY_BCT_FAC_MMODE = "com.ktc.broadcast.factory.mmode";
    public static final String SKY_BCT_FAC_OUTSETOK = "com.ktc.broadcast.factory.outsetok";
    public static final String SKY_BCT_FAC_RECEIVE_STANDBY = "tv.intent.action.standby";
    public static final String SKY_BCT_GETCLOUDSYCDATA = "com.ktc.homepage.showrecomment";
    public static final String SKY_BCT_HOMEPAGE_SWITCH = "com.ktc.broadcast.homepage.switch";
    public static final String SKY_BCT_HOME_ADD_APP_SHORTCUT = "com.ktc.broadcast.home.addShortcut";
    public static final String SKY_BCT_HOME_REMOVE_APP_SHORTCUT = "com.ktc.broadcast.home.removeShortcut";
    public static final String SKY_BCT_HOME_STARTED = "com.ktc.broadcast.homestarted";
    public static final String SKY_BCT_HOME_STATUS = "com.android.sky.homestatus";
    public static final String SKY_BCT_HOTKEYS_3DMODE = "com.ktc.hotkeys.3dmode";
    public static final String SKY_BCT_HOTKEYS_DISABLE = "com.ktc.broadcast.hotkeys.disable";
    public static final String SKY_BCT_HOTKEYS_DISPLAYMODE = "com.ktc.hotkeys.displaymode";
    public static final String SKY_BCT_HOTKEYS_MUTE = "com.ktc.hotkeys.mute";
    public static final String SKY_BCT_HOTKEYS_PICTUREMODE = "com.ktc.hotkeys.picturemode";
    public static final String SKY_BCT_HOTKEYS_SIDEKEYS = "com.ktc.hotkeys.sidekeys";
    public static final String SKY_BCT_HOTKEYS_SOUNDMODE = "com.ktc.hotkeys.soundmode";
    public static final String SKY_BCT_HOTKEYS_SOURCESWITCH = "com.ktc.hotkeys.sourceswitch";
    public static final String SKY_BCT_HOTKEYS_VOLUMEADJUST = "com.ktc.hotkeys.volumeadjust";
    public static final String SKY_BCT_LANG_SETTING_CHANGED = "com.ktc.broadcast.lang.setting";
    public static final String SKY_BCT_LOGACTIVITY = "com.ktc.broadcast.logactivity";
    public static final String SKY_BCT_MEDIAPLAYER_BEGIN = "com.ktc.mediaplayer.begin";
    public static final String SKY_BCT_MEDIAPLAYER_EXIT = "com.ktc.mediaplayer.exit";
    public static final String SKY_BCT_MEDIAPLAYER_OUTEROPEN = "com.ktc.mediaplayer.outeropen";
    public static final String SKY_BCT_MENU_THEME_CHANGED = "com.ktc.themechanged";
    public static final String SKY_BCT_NETWORK_ETHERNET_CONFIGURATION = "com.ktc.broadcast.network.ethernetConfiguration";
    public static final String SKY_BCT_NETWORK_ETHERNET_DEVICE_ADD = "com.ktc.broadcast.network.ethernetDeviceAdd";
    public static final String SKY_BCT_NETWORK_ETHERNET_DEVICE_REMOVE = "com.ktc.broadcast.network.ethernetDeviceRemove";
    public static final String SKY_BCT_NETWORK_ETHERNET_NETWORK_CONNECT = "com.ktc.broadcast.network.ethernetNetworkConnect";
    public static final String SKY_BCT_NETWORK_ETHERNET_NETWORK_DISCONNECT = "com.ktc.broadcast.network.ethernetNetworkDisconnect";
    public static final String SKY_BCT_NETWORK_INTERFACE_CHANGE = "com.ktc.broadcast.network.interfaceChange";
    public static final String SKY_BCT_NETWORK_WIFI_CONFIGURATION = "com.ktc.broadcast.network.wifiConfiguration";
    public static final String SKY_BCT_NETWORK_WIFI_SCAN = "com.ktc.broadcast.network.wifiScan";
    public static final String SKY_BCT_NETWORK_WIFI_WPS_AUTO_CONNECT = "com.ktc.broadcast.network.wifiWpsConfiguration";
    public static final String SKY_BCT_NOTIFY_SETTING_DATA_CHANGED = "com.ktc.broadcast.notify.setting_data_changed";
    public static final String SKY_BCT_PAUSE_AUDIO_PLAY = "com.ktc.broadcast.resource.audioPlay.pause";
    public static final String SKY_BCT_PAUSE_FILESCAN = "com.ktc.broadcast.media_pause_filescan";
    public static final String SKY_BCT_PLAYER_RESOURCE_ACK_RELEASING = "com.ktc.broadcast.resource.player.ackReleasing";
    public static final String SKY_BCT_PLAYER_RESOURCE_AUDIO_PAUSED = "com.ktc.broadcast.resource.audioPlay.pause.done";
    public static final String SKY_BCT_PLAYER_RESOURCE_AUDIO_PAUSING = "com.ktc.broadcast.resource.audioPlay.pause.doing";
    public static final String SKY_BCT_PLAYER_RESOURCE_AUDIO_RESUMED = "com.ktc.broadcast.resource.audioPlay.resume.done";
    public static final String SKY_BCT_PLAYER_RESOURCE_AUDIO_RESUMING = "com.ktc.broadcast.resource.audioPlay.resume.doing";
    public static final String SKY_BCT_PLAYER_RESOURCE_FREE = "com.ktc.broadcast.resource.player.free";
    public static final String SKY_BCT_PLAYER_RESOURCE_INUSE = "com.ktc.broadcast.resource.player.inuse";
    public static final String SKY_BCT_PLAYER_RESOURCE_REQUEST_RELEASE = "com.ktc.broadcast.resource.player.requestRelease";
    public static final String SKY_BCT_PLAYER_RESOURCE_REQUEST_STATE = "com.ktc.broadcast.resource.player.requestState";
    public static final String SKY_BCT_QUICK_STANDBY_RESUME = "com.ktc.broadcast.standby.quick.resume";
    public static final String SKY_BCT_QUICK_STANDBY_SUSPEND = "com.ktc.broadcast.standby.quick.suspend";
    public static final String SKY_BCT_QUIT_WAKE_LOCK = "com.ktc.broadcast.wakelock.quit";
    public static final String SKY_BCT_RECOVERY_FINISH = "com.ktc.broadcast.recovery.finish";
    public static final String SKY_BCT_RECOVERY_START = "com.ktc.broadcast.recovery.start";
    public static final String SKY_BCT_REFRESH_JINSAN_DATA = "com.ktc.broadcast.refresh.jinsan";
    public static final String SKY_BCT_RESUME_AUDIO_PLAY = "com.ktc.broadcast.resource.audioPlay.resume";
    public static final String SKY_BCT_RESUME_FILESCAN = "com.ktc.broadcast.media_resume_filescan";
    public static final String SKY_BCT_SCREEN_SOUND_OFF = "com.ktc.broadcast.screensound.close";
    public static final String SKY_BCT_SCREEN_SOUND_ON = "com.ktc.broadcast.screensound.open";
    public static final String SKY_BCT_SEND_HOTKEYS = "com.android.sky.SendHotKey";
    public static final String SKY_BCT_SEND_KEYPAD = "com.android.sky.ShowKeypadUI";
    public static final String SKY_BCT_SEND_VIRTUAL_KEYPAD = "com.android.sky.ShowVirtualKeypadUI";
    public static final String SKY_BCT_SHOWRECOMMENT = "com.ktc.controlservice.showrecomment";
    public static final String SKY_BCT_SHOW_FOUR_HOURS_UI = "com.ktc.broadcast.show.fourhours.ui";
    public static final String SKY_BCT_SKY_INPUTS_START = "com.ktc.sky.inputstart";
    public static final String SKY_BCT_SKY_INPUTS_STOP = "com.ktc.sky.inputstop";
    public static final String SKY_BCT_SLEEP_TIME_SETTING = "com.ktc.broadcast.sleeptime.setting";
    public static final String SKY_BCT_SNS_SHARE = "com.ktc.broadcast.sns.share";
    public static final String SKY_BCT_SOURCE_SELECT = "com.ktc.broadcast.source.select";
    public static final String SKY_BCT_STANDARDSERVICES_RESTART = "com.ktc.broadcast.standardservices.restart";
    public static final String SKY_BCT_START_INPUT_METHOD = "com.skyworthnj.startinputmethod";
    public static final String SKY_BCT_STOCK_VIEW = "com.ktc.stock.view";
    public static final String SKY_BCT_SWITCH_MODE = "com.ktc.broadcast.switchmode";
    public static final String SKY_BCT_SYSTEM_ENV_CHANGED = "com.ktc.broadcast.system.env";
    public static final String SKY_BCT_SYSTEM_SET_ENV = "com.ktc.broadcast.set.env";
    public static final String SKY_BCT_SYSTEM_STATUS_ENV_CHANGED = "com.ktc.broadcast.status.env";
    public static final String SKY_BCT_TV_ASSISTANT = "com.ktc.tv.assistant";
    public static final String SKY_BCT_TV_ASSISTANT_WEBVIEW = "com.ktc.tv.assistant.web";
    public static final String SKY_BCT_UI_TEXTURESLOADED = "com.ktc.broadcast.ui.texturesloaded";
    public static final String SKY_BCT_UPDATE_TEXT = "com.ktc.controlservice.updatetext";
    public static final String SKY_BCT_VOICE_CLOSE = "com.ktc.voice.close";
    public static final String SKY_BCT_VOICE_FROM_PHONE = "com.ktc.controlservice.voicetext";
    public static final String SKY_BCT_VOICE_KEYS = "com.ktc.voice.key";
    public static final String SKY_BCT_VOICE_SYNTHESIS = "com.ktc.voice.synthesis";
    public static final String SKY_BCT_VOICE_VIEW = "com.ktc.voice.view";
    public static final String SKY_BCT_WEATHER_VIEW = "com.ktc.weather.view";
    public static final String SKY_MOVIE_CHANGED_NOTIFY = "com.ktc.play.moivechanged";
    public static final String SKY_UICOMMONSERCIE_CONNECT = "com.ktc.broadcast.uicommonservice.connect";
    public static final String SKY_UICONTENTVIEWSERCIE_CONNECT = "com.ktc.broadcast.uicontentview.connect";
    public static final String SKY_UIOTHERVIEWSERCIE_CONNECT = "com.ktc.broadcast.uiotherviewservice.connect";
    public static final String SKY_UITVVIEWSERVICE_CONNECT = "com.ktc.broadcast.uitvviewservice.connect";

    public static void registerBroadcast(String str, BroadcastReceiver broadcastReceiver) {
        ///SkyContext.getContext().registerReceiver(broadcastReceiver, new IntentFilter(str));
    }
}
