package com.horion.system.define;

public class KtcConfigDefs {
    @Deprecated
    public static final String KTC_CFG_CHANGE_WIRELESS_AUDIO_ONOFF = "KTC_CFG_CHANGE_WIRELESS_AUDIO_ONOFF";
    public static final String KTC_CFG_DISKINFO_SETTING = "KTC_CFG_DISKINFO_SETTING";
    public static final String KTC_CFG_DISKINFO_SETTING_EXCEPT_INTERNAL_SDCARD = "KTC_CFG_DISKINFO_SETTING_EXCEPT_INTERNAL_SDCARD";
    @Deprecated
    public static final String KTC_CFG_GET_SUPPORT_EQUALIZER = "KTC_CFG_GET_SUPPORT_EQUALIZER";
    @Deprecated
    public static final String KTC_CFG_INFORMATION_GET_SYSTEMINFO = "KTC_CFG_INFORMATION_GET_SYSTEMINFO";
    @Deprecated
    public static final String KTC_CFG_STATISTIC_ENABLED = "enableStatisic";
    public static final String KTC_CFG_TV_3D_DEPTH = "KTC_CFG_TV_3D_DEPTH";
    public static final String KTC_CFG_TV_3D_EFFECT = "KTC_CFG_TV_3D_EFFECT";
    public static final String KTC_CFG_TV_3D_LR_SWAP = "KTC_CFG_TV_3D_LR_SWAP";
    public static final String KTC_CFG_TV_3D_MODE = "KTC_CFG_TV_3D_MODE";
    public static final String KTC_CFG_TV_3D_PANEL = "KTC_CFG_TV_3D_PANEL";
    public static final String KTC_CFG_TV_3D_TO_2D = "KTC_CFG_TV_3D_TO_2D";
    @Deprecated
    public static final String KTC_CFG_TV_4KUI = "KTC_CFG_TV_4KUI";
    public static final String KTC_CFG_TV_4K_HDR = "KTC_CFG_TV_4K_HDR";
    public static final String KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE = "KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE";
    public static final String KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE = "KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE";
    public static final String KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE = "KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE";
    public static final String KTC_CFG_TV_4K_LOCAL_DIMMING = "KTC_CFG_TV_4K_LOCAL_DIMMING";
    public static final String KTC_CFG_TV_4K_MEMC = "KTC_CFG_TV_4K_MEMC";
    @Deprecated
    public static final String KTC_CFG_TV_4K_SWITCH_4K_SOURCE = "KTC_CFG_TV_4K_SWITCH_4K_SOURCE";
    public static final String KTC_CFG_TV_AI_VOLUME_ADJUST = "KTC_CFG_TV_AI_VOLUME_ADJUST";
    public static final String KTC_CFG_TV_ANOLOG_AUDIO_OUTPUT = "KTC_CFG_TV_ANOLOG_AUDIO_OUTPUT";
    public static final String KTC_CFG_TV_ATMOS_DRC = "KTC_CFG_TV_ATMOS_DRC";
    public static final String KTC_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME = "KTC_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME";
    public static final String KTC_CFG_TV_ATMOS_MIDDLE_VOLUME = "KTC_CFG_TV_ATMOS_MIDDLE_VOLUME";
    public static final String KTC_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST = "KTC_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST";
    public static final String KTC_CFG_TV_ATMOS_SCENE_SELECT = "KTC_CFG_TV_ATMOS_SCENE_SELECT";
    public static final String KTC_CFG_TV_ATMOS_SOUND_EFFECTS = "KTC_CFG_TV_ATMOS_SOUND_EFFECTS";
    public static final String KTC_CFG_TV_ATMOS_SUBWOOFER_VOLUME = "KTC_CFG_TV_ATMOS_SUBWOOFER_VOLUME";
    public static final String KTC_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST = "KTC_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST";
    public static final String KTC_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST = "KTC_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST";
    public static final String KTC_CFG_TV_AUDIO_MUTE = "KTC_CFG_TV_AUDIO_MUTE";
    public static final String KTC_CFG_TV_AUDIO_OUTPUT = "KTC_CFG_TV_AUDIO_OUTPUT";
    @Deprecated
    public static final String KTC_CFG_TV_AVL = "KTC_CFG_TV_AVL";
    @Deprecated
    public static final String KTC_CFG_TV_AV_COLOR_SYSTEM = "KTC_CFG_TV_AV_COLOR_SYSTEM";
    @Deprecated
    public static final String KTC_CFG_TV_BALANCE = "KTC_CFG_TV_BALANCE";
    public static final String KTC_CFG_TV_BASS = "KTC_CFG_TV_BASS";
    @Deprecated
    public static final String KTC_CFG_TV_BASS_REDUCTION = "KTC_CFG_TV_BASS_REDUCTION";
    public static final String KTC_CFG_TV_BREATH_LIGHT_SWITCH = "KTC_CFG_TV_BREATH_LIGHT_SWITCH";
    public static final String KTC_CFG_TV_BRIGHTNESS = "KTC_CFG_TV_BRIGHTNESS";
    public static final String KTC_CFG_TV_BUILD_SERVER = "KTC_CFG_TV_BUILD_SERVER";
    @Deprecated
    public static final String KTC_CFG_TV_CHILD_LOCK = "KTC_CFG_TV_CHILD_LOCK";
    @Deprecated
    public static final String KTC_CFG_TV_CINEMA_MODE = "KTC_CFG_TV_CINEMA_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_CLEAR_PAD_REBOOT_CNT = "KTC_CFG_TV_CLEAR_PAD_REBOOT_CNT";
    public static final String KTC_CFG_TV_CLOSE_SCREEN_SOUND_SWITCH = "KTC_CFG_TV_CLOSE_SCREEN_SOUND_SWITCH";
    public static final String KTC_CFG_TV_COLOR = "KTC_CFG_TV_COLOR";
    public static final String KTC_CFG_TV_COLOR_TEMPERATURE = "KTC_CFG_TV_COLOR_TEMPERATURE";
    @Deprecated
    public static final String KTC_CFG_TV_COMMON_DEMO = "KTC_CFG_TV_COMMON_DEMO";
    public static final String KTC_CFG_TV_CONTRAST = "KTC_CFG_TV_CONTRAST";
    public static final String KTC_CFG_TV_DIGITAL_AUDIO_OUTPUT = "KTC_CFG_TV_DIGITAL_AUDIO_OUTPUT";
    public static final String KTC_CFG_TV_DISPLAY_MODE = "KTC_CFG_TV_DISPLAY_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_DISPLAY_MODE_4K = "KTC_CFG_TV_DISPLAY_MODE_4K";
    public static final String KTC_CFG_TV_DISPLAY_OVER_SCAN = "KTC_CFG_TV_DISPLAY_OVER_SCAN";
    public static final String KTC_CFG_TV_DNR = "KTC_CFG_TV_DNR";
    public static final String KTC_CFG_TV_DREAM_PANEL = "KTC_CFG_TV_DREAM_PANEL";
    @Deprecated
    public static final String KTC_CFG_TV_DREAM_PANEL_DEMO_FLAG = "KTC_CFG_TV_DREAM_PANEL_DEMO_FLAG";
    @Deprecated
    public static final String KTC_CFG_TV_DREAM_PANEL_SWITCH = "KTC_CFG_TV_DREAM_PANEL_SWITCH";
    public static final String KTC_CFG_TV_DYNAMIC_CONTRAST = "KTC_CFG_TV_DYNAMIC_CONTRAST";
    public static final String KTC_CFG_TV_EDID = "KTC_CFG_TV_EDID";
    public static final String KTC_CFG_TV_EQUALIZER = "KTC_CFG_TV_EQUALIZER";
    public static final String KTC_CFG_TV_EQUALIZER_100HZ = "KTC_CFG_TV_EQUALIZER_100HZ";
    public static final String KTC_CFG_TV_EQUALIZER_10KHZ = "KTC_CFG_TV_EQUALIZER_10KHZ";
    public static final String KTC_CFG_TV_EQUALIZER_1K5HZ = "KTC_CFG_TV_EQUALIZER_1K5HZ";
    @Deprecated
    public static final String KTC_CFG_TV_EQUALIZER_1KHZ = "KTC_CFG_TV_EQUALIZER_1KHZ";
    @Deprecated
    public static final String KTC_CFG_TV_EQUALIZER_3KHZ = "KTC_CFG_TV_EQUALIZER_3KHZ";
    public static final String KTC_CFG_TV_EQUALIZER_500HZ = "KTC_CFG_TV_EQUALIZER_500HZ";
    public static final String KTC_CFG_TV_EQUALIZER_5KHZ = "KTC_CFG_TV_EQUALIZER_5KHZ";
    @Deprecated
    public static final String KTC_CFG_TV_EXTERNAL_STORAGE_IDENTIFICATION = "KTC_CFG_TV_EXTERNAL_STORAGE_IDENTIFICATION";
    public static final String KTC_CFG_TV_EYE_PROTECTED = "KTC_CFG_TV_EYE_PROTECTED";
    @Deprecated
    public static final String KTC_CFG_TV_FACTORY_SETUP_PANEL_SWING = "KTC_CFG_TV_FACTORY_SETUP_PANEL_SWING";
    @Deprecated
    public static final String KTC_CFG_TV_FACTORY_SETUP_WOLE_STATUS = "KTC_CFG_TV_FACTORY_SETUP_WOLE_STATUS";
    public static final String KTC_CFG_TV_FACTORY_SINGLE_KEY = "KTC_CFG_TV_FACTORY_SINGLE_KEY";
    public static final String KTC_CFG_TV_HDMI_OUTPUT = "KTC_CFG_TV_HDMI_OUTPUT";
    public static final String KTC_CFG_TV_HDR_DEMO = "KTC_CFG_TV_HDR_DEMO";
    @Deprecated
    public static final String KTC_CFG_TV_HOMEPAGE_SWITCH = "KTC_CFG_TV_HOMEPAGE_SWITCH";
    public static final String KTC_CFG_TV_HUE = "KTC_CFG_TV_HUE";
    public static final String KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_DEMO = "KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_DEMO";
    @Deprecated
    public static final String KTC_CFG_TV_IQIYI_PLAYER = "KTC_CFG_TV_IQIYI_PLAYER";
    @Deprecated
    public static final String KTC_CFG_TV_IS_4K2K_MODE = "KTC_CFG_TV_IS_4K2K_MODE";
    public static final String KTC_CFG_TV_IS_SUPPORT_CLOSE_SCREEN_SOUND = "KTC_CFG_TV_IS_SUPPORT_CLOSE_SCREEN_SOUND";
    public static final String KTC_CFG_TV_IS_SUPPORT_SCREENSHOT = "KTC_CFG_TV_IS_SUPPORT_SCREENSHOT";
    public static final String KTC_CFG_TV_IS_SUPPORT_STR_STANDBY = "KTC_CFG_TV_IS_SUPPORT_STR_STANDBY";
    @Deprecated
    public static final String KTC_CFG_TV_KEY_VOLUME = "KTC_CFG_TV_KEY_VOLUME";
    @Deprecated
    public static final String KTC_CFG_TV_LANGUAGE = "KTC_CFG_TV_LANGUAGE";
    public static final String KTC_CFG_TV_LED_CONTROL = "KTC_CFG_TV_LED_CONTROL";
    public static final String KTC_CFG_TV_LOCAL_DIMMING_MODE = "KTC_CFG_TV_LOCAL_DIMMING_MODE";
    public static final String KTC_CFG_TV_MANUAL_BACKLIGHT_ADJUST = "KTC_CFG_TV_MANUAL_BACKLIGHT_ADJUST";
    @Deprecated
    public static final String KTC_CFG_TV_MEMC_120HZ_DEMO_MODE = "KTC_CFG_TV_MEMC_120HZ_DEMO_MODE";
    public static final String KTC_CFG_TV_MEMC_MODE = "KTC_CFG_TV_MEMC_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_MEMC_SWITCH = "KTC_CFG_TV_MEMC_SWITCH";
    public static final String KTC_CFG_TV_MENU_FILE_PATH = "KTC_CFG_TV_MENU_FILE_PATH";
    @Deprecated
    public static final String KTC_CFG_TV_MICROPHONE_DEVICE = "KTC_CFG_TV_MICROPHONE_DEVICE";
    public static final String KTC_CFG_TV_MOVIE_MODE = "KTC_CFG_TV_MOVIE_MODE";
    public static final String KTC_CFG_TV_MPEG_DNR = "KTC_CFG_TV_MPEG_DNR";
    @Deprecated
    public static final String KTC_CFG_TV_MPEG_NR = "KTC_CFG_TV_MPEG_NR";
    public static final String KTC_CFG_TV_MUSIC_LIGHT = "KTC_CFG_TV_MUSIC_LIGHT";
    @Deprecated
    public static final String KTC_CFG_TV_NEED_RELEASE_BEFORE_REBOOT = "KTC_CFG_TV_NEED_RELEASE_BEFORE_REBOOT";
    public static final String KTC_CFG_TV_OLED_SCREEN_FIX_OFFRS_TIME = "KTC_CFG_TV_OLED_SCREEN_FIX_OFFRS_TIME";
    public static final String KTC_CFG_TV_PANEL_SIZE = "KTC_CFG_TV_PANEL_SIZE";
    public static final String KTC_CFG_TV_PICTURE_MODE = "KTC_CFG_TV_PICTURE_MODE";
    public static final String KTC_CFG_TV_POWER_OFF = "KTC_CFG_TV_POWER_OFF";
    @Deprecated
    public static final String KTC_CFG_TV_POWER_ONOFF_MUSIC = "KTC_CFG_TV_POWER_ONOFF_MUSIC";
    @Deprecated
    public static final String KTC_CFG_TV_POWER_ONOFF_MUSIC_VOLUME = "KTC_CFG_TV_POWER_ONOFF_MUSIC_VOLUME";
    public static final String KTC_CFG_TV_POWER_ON_MODE = "KTC_CFG_TV_POWER_ON_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_PREPMPLAYER_DISPLAY_MODE = "KTC_CFG_TV_PREPMPLAYER_DISPLAY_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_REAL_3D_MODE = "KTC_CFG_TV_REAL_3D_MODE";
    @Deprecated
    public static final String KTC_CFG_TV_REAL_COLOR_SYSTEM = "KTC_CFG_TV_REAL_COLOR_SYSTEM";
    public static final String KTC_CFG_TV_REBOOT_SYSTEM = "KTC_CFG_TV_REBOOT_SYSTEM";
    public static final String KTC_CFG_TV_RECOVERY = "KTC_CFG_TV_RECOVERY";
    public static final String KTC_CFG_TV_RESET_PICTURE_SETS = "KTC_CFG_TV_RESET_PICTURE_SETS";
    public static final String KTC_CFG_TV_RESET_SOUND_SETS = "KTC_CFG_TV_RESET_SOUND_SETS";
    public static final String KTC_CFG_TV_RESOLUTION = "KTC_CFG_TV_RESOLUTION";
    public static final String KTC_CFG_TV_SCREENSHOT = "KTC_CFG_TV_SCREENSHOT";
    public static final String KTC_CFG_TV_SCREENSHOT_IS_ONLY_HAVE_VIDEO_LAYER = "KTC_CFG_TV_SCREENSHOT_IS_ONLY_HAVE_VIDEO_LAYER";
    public static final String KTC_CFG_TV_SET_LOCATION = "KTC_CFG_TV_SET_LOCATION";
    @Deprecated
    public static final String KTC_CFG_TV_SET_SCREENSAVER = "KTC_CFG_TV_SET_SCREENSAVER";
    public static final String KTC_CFG_TV_SET_SCREEN_SOUND = "KTC_CFG_TV_SET_SCREEN_SOUND";
    public static final String KTC_CFG_TV_SHARPNESS = "KTC_CFG_TV_SHARPNESS";
    public static final String KTC_CFG_TV_SLEEP_TIMER = "KTC_CFG_TV_SLEEP_TIMER";
    public static final String KTC_CFG_TV_SOUNDBAR_MODE = "KTC_CFG_TV_SOUNDBAR_MODE";
    public static final String KTC_CFG_TV_SOUND_BALANCE = "KTC_CFG_TV_SOUND_BALANCE";
    @Deprecated
    public static final String KTC_CFG_TV_SOUND_CLARITY = "KTC_CFG_TV_SOUND_CLARITY";
    @Deprecated
    public static final String KTC_CFG_TV_SOUND_LIVESOUND = "KTC_CFG_TV_SOUND_LIVESOUND";
    public static final String KTC_CFG_TV_SOUND_MODE = "KTC_CFG_TV_SOUND_MODE";
    public static final String KTC_CFG_TV_SOUND_SEPERATE = "KTC_CFG_TV_SOUND_SEPERATE";
    public static final String KTC_CFG_TV_SOUND_SPDIF = "KTC_CFG_TV_SOUND_SPDIF";
    @Deprecated
    public static final String KTC_CFG_TV_SOURCE_STORAGE = "KTC_CFG_TV_SOURCE_STORAGE";
    public static final String KTC_CFG_TV_STANDBY_MODE_QUICK = "KTC_CFG_TV_STANDBY_MODE_QUICK";
    public static final String KTC_CFG_TV_STICKER_DEMO = "KTC_CFG_TV_STICKER_DEMO";
    @Deprecated
    public static final String KTC_CFG_TV_SUBWOOFER = "KTC_CFG_TV_SUBWOOFER";
    public static final String KTC_CFG_TV_SUBWOOFER_VOLUME = "KTC_CFG_TV_SUBWOOFER_VOLUME";
    public static final String KTC_CFG_TV_SURROUND = "KTC_CFG_TV_SURROUND";
    @Deprecated
    public static final String KTC_CFG_TV_SWITCH_BY_PASS = "KTC_CFG_TV_SWITCH_BY_PASS";
    public static final String KTC_CFG_TV_SYSTEM_OWNER = "KTC_CFG_TV_SYSTEM_OWNER";
    public static final String KTC_CFG_TV_THREED_SETTING = "KTC_CFG_TV_THREED_SETTING";
    public static final String KTC_CFG_TV_TOUCH_LOGO_SWITCH = "KTC_CFG_TV_TOUCH_LOGO_SWITCH";
    @Deprecated
    public static final String KTC_CFG_TV_TRACK_SWITCH = "KTC_CFG_TV_TRACK_SWITCH";
    public static final String KTC_CFG_TV_TREBLE = "KTC_CFG_TV_TREBLE";
    @Deprecated
    public static final String KTC_CFG_TV_TRUBASS = "KTC_CFG_TV_TRUBASS";
    public static final String KTC_CFG_TV_TVNAME = "KTC_CFG_TV_TVNAME";
    public static final String KTC_CFG_TV_UNIQUE_IDENTIFICATION_CODE = "KTC_CFG_TV_UNIQUE_IDENTIFICATION_CODE";
    public static final String KTC_CFG_TV_USER_HISTORY = "KTC_CFG_TV_USER_HISTORY";
    public static final String KTC_CFG_TV_USE_ENVIRONMENT = "KTC_CFG_TV_USE_ENVIRONMENT";
    public static final String KTC_CFG_TV_VIDEO_STREAM_TYPE = "KTC_CFG_TV_VIDEO_STREAM_TYPE";
    @Deprecated
    public static final String KTC_CFG_TV_VOICE_READER = "KTC_CFG_TV_VOICE_READER";
    public static final String KTC_CFG_TV_VOLUME = "KTC_CFG_TV_VOLUME";
    @Deprecated
    public static final String KTC_CFG_TV_WALL_SOUND_EFFECTS = "KTC_CFG_TV_WALL_SOUND_EFFECTS";

    @Deprecated
    public enum KTC_CFG_TV_3D_EFFECT_ENUM_TYPE {
        KTC_CFG_TV_3D_EFFECT_LOW,
        KTC_CFG_TV_3D_EFFECT_MID,
        KTC_CFG_TV_3D_EFFECT_HIGH,
        KTC_CFG_TV_3D_EFFECT_INVALID
    }

    public enum KTC_CFG_TV_3D_MODE_ENUM_TYPE {
        KTC_CFG_TV_3D_MODE_OFF,
        KTC_CFG_TV_3D_MODE_AUTO,
        KTC_CFG_TV_3D_MODE_SIDE_BY_SIDE,
        KTC_CFG_TV_3D_MODE_TOP_AND_BOTTOM,
        KTC_CFG_TV_3D_MODE_FRAME_PACKING,
        KTC_CFG_TV_3D_MODE_INVALID
    }

    public enum KTC_CFG_TV_3D_TO_2D_ENUM_TYPE {
        KTC_CFG_TV_3D_TO_2D_OFF,
        KTC_CFG_TV_3D_TO_2D_LEFT,
        KTC_CFG_TV_3D_TO_2D_RIGHT,
        KTC_CFG_TV_3D_TO_2D_INVALID
    }

    @Deprecated
    public enum KTC_CFG_TV_4KUI_ENUM_TYPE {
        KTC_CFG_TV_4KUI_OPEN,
        KTC_CFG_TV_4KUI_CLOSE
    }

    public enum KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_ENUM_TYPE {
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_WEAK,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_MIDDLE,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_STRONG,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_CLOSE,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_AUTO,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_COMPENSATE_INVALID
    }

    public enum KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_ENUM_TYPE {
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_RIGHT,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_FULLSCREEN,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_CLOSE,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_OPEN,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_DEMO_MODE_INVALID
    }

    public enum KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE_ENUM_TYPE {
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE_OPEN,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE_DEMO,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE_CLOSE,
        KTC_CFG_TV_4K_IMAGE_ENHANCEMENT_PROCESSING_ENGINE_INVALID
    }

    public enum KTC_CFG_TV_ANOLOG_AUDIO_OUTPUT_ENUM_TYPE {
        KTC_CFG_TV_ANOLOG_AUDIO_OUTPUT_LINEOUT,
        KTC_CFG_TV_ANOLOG_AUDIO_OUTPUT_HEADPHONE
    }

    public enum KTC_CFG_TV_ATMOS_DRC_ENUM_TYPE {
        KTC_CFG_TV_ATMOS_DRC_ON,
        KTC_CFG_TV_ATMOS_DRC_OFF,
        KTC_CFG_TV_ATMOS_DRC_AUTO
    }

    public enum KTC_CFG_TV_ATMOS_SCENE_SELECT_ENUM_TYPE {
        KTC_CFG_TV_ATMOS_SCENE_SELECT_STANDARD,
        KTC_CFG_TV_ATMOS_SCENE_SELECT_LIVING_ROOM,
        KTC_CFG_TV_ATMOS_SCENE_SELECT_BEDROOM,
        KTC_CFG_TV_ATMOS_SCENE_SELECT_OTHER
    }

    public enum KTC_CFG_TV_AUDIO_OUTPUT_ENUM_TYPE {
        KTC_CFG_TV_AUDIO_OUTPUT_EXTERNAL,
        KTC_CFG_TV_AUDIO_OUTPUT_INTERNAL,
        KTC_CFG_TV_AUDIO_OUTPUT_MIX
    }

    public enum KTC_CFG_TV_COLOR_TEMPERATURE_ENUM_TYPE {
        KTC_CFG_TV_COLOR_TEMPERATURE_WARM,
        KTC_CFG_TV_COLOR_TEMPERATURE_STANDARD,
        KTC_CFG_TV_COLOR_TEMPERATURE_COOL,
        KTC_CFG_TV_COLOR_TEMPERATURE_INVALID
    }

    public enum KTC_CFG_TV_DIGITAL_AUDIO_OUTPUT_ENUM_TYPE {
        KTC_CFG_TV_DIGITAL_AUDIO_OUTPUT_AUTO,
        KTC_CFG_TV_DIGITAL_AUDIO_OUTPUT_PCM
    }

    public enum KTC_CFG_TV_DISPLAY_MODE_4K_ENUM_TYPE {
        KTC_CFG_TV_PICTURE_4K_DISPLAY,
        KTC_CFG_TV_PICTURE_HIGH_DISPLAY,
        KTC_CFG_TV_DISPLAY_MODE_4K_INVALID
    }

    public enum KTC_CFG_TV_DISPLAY_MODE_ENUM_TYPE {
        KTC_CFG_TV_DISPLAY_MODE_16_9,
        KTC_CFG_TV_DISPLAY_MODE_4_3,
        KTC_CFG_TV_DISPLAY_MODE_AUTO,
        KTC_CFG_TV_DISPLAY_MODE_MOVIE,
        KTC_CFG_TV_DISPLAY_MODE_CAPTION,
        KTC_CFG_TV_DISPLAY_MODE_PANORAMA,
        KTC_CFG_TV_DISPLAY_MODE_PERSON,
        KTC_CFG_TV_DISPLAY_MODE_INVALID
    }

    public enum KTC_CFG_TV_DNR_ENUM_TYPE {
        KTC_CFG_TV_DNR_OFF,
        KTC_CFG_TV_DNR_LOW,
        KTC_CFG_TV_DNR_MID,
        KTC_CFG_TV_DNR_HIGH,
        KTC_CFG_TV_DNR_AUTO,
        KTC_CFG_TV_DNR_INVALID
    }

    public enum KTC_CFG_TV_DREAM_PANEL_ENUM_TYPE {
        KTC_CFG_TV_DREAM_PANEL_OFF,
        KTC_CFG_TV_DREAM_PANEL_LIGHT_SENSOR,
        KTC_CFG_TV_DREAM_PANEL_IMAGE_DETECT,
        KTC_CFG_TV_DREAM_PANEL_MULTI_DETECT,
        KTC_CFG_TV_DREAM_PANEL_DEMO,
        KTC_CFG_TV_DREAM_PANEL_INVALID
    }

    public enum KTC_CFG_TV_HDMI_OUTPUT_ENUM_TYPE {
        KTC_CFG_TV_HDMI_OUTPUT_AUTO,
        KTC_CFG_TV_HDMI_OUTPUT_RAW
    }

    public enum KTC_CFG_TV_HDR_DEMO_ENUM_TYPE {
        E_TV_HDR_DEMO_OPEN,
        E_TV_HDR_DEMO_CLOSE
    }

    public enum KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_DEMO_ENUM_TYPE {
        KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_OPEN,
        KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_CLOSE,
        KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_DEMO_DEMO,
        KTC_CFG_TV_INFORMATION_GET_PANEL_COLOR_DEPTH_DEMO_INVALID
    }

    public enum KTC_CFG_TV_LED_CONTROL_ENUM_TYPE {
        KTC_CFG_TV_LED_CONTROL_CLOSE,
        KTC_CFG_TV_LED_CONTROL_RED,
        KTC_CFG_TV_LED_CONTROL_BLUE,
        KTC_CFG_TV_LED_CONTROL_PURPLE,
        KTC_CFG_TV_LED_CONTROL_FLASH,
        KTC_CFG_TV_LED_CONTROL_OPEN,
        KTC_CFG_TV_LED_CONTROL_HIGH_LIGHT
    }

    public enum KTC_CFG_TV_LOCAL_DIMMING_MODE_ENUM_TYPE {
        KTC_CFG_TV_LOCAL_DIMMING_OFF_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_ON_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_DEMO_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_INVALID_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_HIGH_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_LOW_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_MID_MODE
    }

    public enum KTC_CFG_TV_LOCAL_DIMMING_MODE_NO_BACKLIGHT_ENUM_TYPE {
        KTC_CFG_TV_LOCAL_DIMMING_OFF_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_ON_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_LOW_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_MID_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_HIGH_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_DEMO_MODE,
        KTC_CFG_TV_LOCAL_DIMMING_INVALID_MODE
    }

    @Deprecated
    public enum KTC_CFG_TV_MEMC_120HZ_DEMO_MODE_ENUM_TYPE {
        KTC_CFG_TV_MEMC_120HZ_DEMO_OFF,
        KTC_CFG_TV_MEMC_120HZ_DEMO_LEFT_RIGHT,
        KTC_CFG_TV_MEMC_120HZ_DEMO_UP_DOWN,
        KTC_CFG_TV_MEMC_120HZ_DEMO_FULL_SCREEN,
        KTC_CFG_TV_MEMC_120HZ_DEMO_INVALID
    }

    public enum KTC_CFG_TV_MEMC_MODE_ENUM_TYPE {
        KTC_CFG_TV_MEMC_MODE_OFF,
        KTC_CFG_TV_MEMC_MODE_LOW,
        KTC_CFG_TV_MEMC_MODE_MID,
        KTC_CFG_TV_MEMC_MODE_HIGH,
        KTC_CFG_TV_MEMC_MODE_INAVLID
    }

    public enum KTC_CFG_TV_MUSIC_LIGHT_ENUM_TYPE {
        KTC_CFG_TV_MUSIC_LIGHT_HIGH,
        KTC_CFG_TV_MUSIC_LIGHT_MID,
        KTC_CFG_TV_MUSIC_LIGHT_LOW,
        KTC_CFG_TV_MUSIC_LIGHT_OFF
    }

    public enum KTC_CFG_TV_ON_OFF_MODE_ENUM_TYPE {
        KTC_CFG_TV_OFF_MODE,
        KTC_CFG_TV_ON_MODE,
        KTC_CFG_TV_ON_OFF_INVALID
    }

    public enum KTC_CFG_TV_PICTURE_MODE_ENUM_TYPE {
        KTC_CFG_TV_PICTURE_MODE_STANDARD,
        KTC_CFG_TV_PICTURE_MODE_VIVID,
        KTC_CFG_TV_PICTURE_MODE_GENTLE,
        KTC_CFG_TV_PICTURE_MODE_USER,
        KTC_CFG_TV_PICTURE_MODE_4K_CINEMA,
        KTC_CFG_TV_PICTURE_MODE_GAME,
        KTC_CFG_TV_PICTURE_MODE_DOLBY_VISION_MOVIE_DARK,
        KTC_CFG_TV_PICTURE_MODE_DOLBY_VISION_MOVIE_BRIGHT,
        KTC_CFG_TV_PICTURE_MODE_PROFESSIONAL,
        KTC_CFG_TV_PICTURE_MODE_SPORT,
        KTC_CFG_TV_PICTURE_MODE_MOVIE,
        KTC_CFG_TV_PICTURE_MODE_DYNAMIC,
        KTC_CFG_TV_PICTURE_MODE_INVALID
    }

    public enum KTC_CFG_TV_POWER_ON_MODE_ENUM_TYPE {
        KTC_CFG_TV_POWER_ON_MODE_STANDBY,
        KTC_CFG_TV_POWER_ON_MODE_BOOT
    }

    public enum KTC_CFG_TV_REAL_3D_MODE_ENUM_TYPE {
        KTC_CFG_TV_REAL_3D_MODE_2D,
        KTC_CFG_TV_REAL_3D_MODE_3D
    }

    public enum KTC_CFG_TV_RESOLUTION_ENUM_TYPE {
        KTC_CFG_TV_RESOLUTION_AUTO,
        KTC_CFG_TV_RESOLUTION_720p_50Hz,
        KTC_CFG_TV_RESOLUTION_720p_60Hz,
        KTC_CFG_TV_RESOLUTION_1080i_50Hz,
        KTC_CFG_TV_RESOLUTION_1080i_60Hz,
        KTC_CFG_TV_RESOLUTION_1080p_50Hz,
        KTC_CFG_TV_RESOLUTION_1080p_60Hz
    }

    public enum KTC_CFG_TV_SOUND_MODE_ENUM_TYPE {
        KTC_CFG_TV_SOUND_MODE_STANDARD,
        KTC_CFG_TV_SOUND_MODE_MUSIC,
        KTC_CFG_TV_SOUND_MODE_NEWS,
        KTC_CFG_TV_SOUND_MODE_MOVIE,
        KTC_CFG_TV_SOUND_MODE_3D_MOVIE_EFFECT,
        KTC_CFG_TV_SOUND_MODE_USER,
        KTC_CFG_TV_SOUND_MODE_SPORT,
        KTC_CFG_TV_SOUND_MODE_INVALID
    }

    public enum KTC_CFG_TV_SOUND_SPDIF_ENUM_TYPE {
        KTC_CFG_TV_SOUND_SPDIF_SOURCE,
        KTC_CFG_TV_SOUND_SPDIF_PCM,
        KTC_CFG_TV_SOUND_SPDIF_INVALID
    }

    public enum KTC_CFG_TV_USE_ENVIRONMENT_ENUM_TYPE {
        KTC_CFG_TV_USE_ENVIRONMENT_HOME,
        KTC_CFG_TV_USE_ENVIRONMENT_STORE
    }

    public enum KTC_CFG_TV_VIDEO_STREAM_TYPE_ENUM_TYPE {
        KTC_CFG_TV_VIDEO_STREAM_TYPE_UNKNOWN,
        KTC_CFG_TV_VIDEO_STREAM_TYPE_SDR,
        KTC_CFG_TV_VIDEO_STREAM_TYPE_HDR10,
        KTC_CFG_TV_VIDEO_STREAM_TYPE_DOLBY_HDR
    }

    @Deprecated
    public enum KTC_CONFIG_SET {
        KTC_CFG_TV_SOUND_SETTING,
        KTC_CFG_TV_PICTURE_SETTING,
        KTC_CFG_TV_ADVANCED_SETTING,
        KTC_CFG_TV_SYSTEM_SETTING,
        KTC_CFG_TV_THREED_SETTING
    }

    public enum KTC_SYSTEM_ENV_START_SCREEN_SAVER_MODE_ENUM_TYPE {
        ONE_MIN,
        TWO_MIN,
        FIVE_MIN,
        TEN_MIN,
        THIRTY_MIN,
        NONE
    }

    @Deprecated
    public enum KtcConfigSoundEffectModeType {
        KTC_CFG_TV_SOUND_EFFECT_MODE_OFF,
        KTC_CFG_TV_SOUND_EFFECT_MODE_EFFECT_1,
        KTC_CFG_TV_SOUND_EFFECT_MODE_EFFECT_2,
        KTC_CFG_TV_SOUND_EFFECT_MODE_EFFECT_3,
        KTC_CFG_TV_SOUND_EFFECT_MODE_INVALID
    }
}
